#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# skftool - may the weeaboo be with you
#
# Author: slowpoke <mail+git@slowpoke.io>
#
# This program is Free Software under the non-terms
# of the Anti-License. Do whatever the fuck you want.
#
# Github: https://www.github.com/proxypoke/skftool
